### ISSUE TITLE
请问作者有在官方的pytorch或者tensorflow的代码吗

### ISSUE THREAD

**Issue by ChauvinisticJonatha** [EndyWon/Deep-Feature-Perturbation#1]

**Comment by EndyWon** [comment]
Currently, it has not been implemented on the official pytorch or tensorflow of WCT, but you can easily realize it by simply adding a few lines of codes to them, just like line 217-229 and 240-243 of our test_wct_DFP.lua

**Comment by ChauvinisticJonatha** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhizhong Wang"<notifications@github.com&gt;; 
发送时间: 2020年12月13日(星期天) 晚上7:21
收件人: "EndyWon/Deep-Feature-Perturbation"<Deep-Feature-Perturbation@noreply.github.com&gt;; 
抄送: "张占杰"<1097234580@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [EndyWon/Deep-Feature-Perturbation] 请问作者有在官方的pytorch或者tensorflow的代码吗 (#1)





 
Currently, it has not been implemented on the official pytorch or tensorflow of WCT, but you can easily realize it by simply adding a few lines of codes to them, just like line 217-229 and 240-243 of our test_wct_DFP.lua

**Comment by ChauvinisticJonatha** [comment]
> Currently, it has not been implemented on the official pytorch or tensorflow of WCT, but you can easily realize it by simply adding a few lines of codes to them, just like line 217-229 and 240-243 of our test_wct_DFP.lua

HellopCan you release a pytorch or tensorflor code? I try to add your code to PyTorch implementation I by Xueting Li.  But, limited capacity because I work. I want to cite this paper in my paper. The  implementation of official lua is too old. My hardware can't support cuda7.0/8.0

**Comment by ChauvinisticJonatha** [comment]
> thank you
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zhizhong Wang"<notifications@github.com&gt;; 发送时间: 2020年12月13日(星期天) 晚上7:21 收件人: "EndyWon/Deep-Feature-Perturbation"<Deep-Feature-Perturbation@noreply.github.com&gt;; 抄送: "张占杰"<1097234580@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [EndyWon/Deep-Feature-Perturbation] 请问作者有在官方的pytorch或者tensorflow的代码吗 (#1) Currently, it has not been implemented on the official pytorch or tensorflow of WCT, but you can easily realize it by simply adding a few lines of codes to them, just like line 217-229 and 240-243 of our test_wct_DFP.lua — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> Currently, it has not been implemented on the official pytorch or tensorflow of WCT, but you can easily realize it by simply adding a few lines of codes to them, just like line 217-229 and 240-243 of our test_wct_DFP.lua

Hello, my dear. Can you release a pytorch or tensorflor code? I try to add your code to PyTorch implementation I by Xueting Li. But, limited capacity because I work. I failed to add 240-243 code. I want to cite this paper in my paper. The implementation of official lua is too old. My hardware can't support cuda7.0/8.0.

**Comment by EndyWon** [comment]
Sorry for the late reply, I will upload a tensorflow code about incorporating our DFP into Avatar-Net. 
I hope this could help you.

**Comment by EndyWon** [comment]
The pytorch code for PhotoWCT will be uploaded as well.
